#static code analysis by sonarqube
- name: 'maven:3.6.1-jdk-8'
  entrypoint: 'bash'
  args:
    - -c
    - |
      unset MAVEN_CONFIG \
      && echo "104.199.71.165 sonarqube.ct.blue.cdtapps.com" > /etc/hosts \
      && mvn sonar:sonar -q -Dsonar.login=5531b1a2d571c0482a3d89f605830e08ccf5f850 \
      '-Dsonar.projectKey=odp.df.pubsub-sftp' \
      '-Dsonar.projectName=ODP-DF-PUBSUB-SFTP' \
      '-Dsonar.host.url=https://sonarqube.ct.blue.cdtapps.com' \
      '-Dsonar.qualitygate.wait=true' \
      'allow_failure: true'
  dir: 'dataflows/generic/pubsub-sftp/src'
  id: 'sonarqube-analysis'
